### ISSUE TITLE
Recap: a lot of code is dead in assert() statements

### ISSUE THREAD

**Issue by quiret** [aap/librw#5]
Examples:
https://github.com/aap/librw/blob/master/src/image.cpp#L65
https://github.com/aap/librw/blob/master/src/image.cpp#L179
https://github.com/aap/librw/blob/master/src/image.cpp#L241
https://github.com/aap/librw/blob/master/src/geometry.cpp#L106
- it never finds the chunk if asserts are disabled

https://github.com/aap/librw/blob/master/src/image.cpp#L528
- it never opens the file for writing TGA if asserts are disabled

In Release mode, some compilers like to put the preprocessor definition "NDEBUG" to disable things like the "assert" macro to speed up code. In return, your code breaks because assert statements do not execute in Release mode anymore. Please take a look at this issue. :)

**Comment by JayFoxRox** [comment]
I've fixed these links for you. I believe all of those have been fixed

https://github.com/aap/librw/blob/290117e9be6f75ea2d480a5600fc091b2ffaf9dc/src/image.cpp#L65
https://github.com/aap/librw/blob/290117e9be6f75ea2d480a5600fc091b2ffaf9dc/src/image.cpp#L179
https://github.com/aap/librw/blob/290117e9be6f75ea2d480a5600fc091b2ffaf9dc/src/image.cpp#L241
https://github.com/aap/librw/blob/290117e9be6f75ea2d480a5600fc091b2ffaf9dc/src/geometry.cpp#L106

 (the one in `writeTGA` has been moved to tga.cpp since)

https://github.com/aap/librw/blob/290117e9be6f75ea2d480a5600fc091b2ffaf9dc/src/image.cpp#L528

---

@aap this can be closed
