### ISSUE TITLE
Recap: interrupting the program on error is inacceptable for networked games

### ISSUE THREAD

**Issue by quiret** [aap/librw#6]
In your library you like to use the assert statement to halt program execution if an error occurred. We are currently programming a game engine that uses your library and are worried about that. What if we allow loading of resources into our engine that are not verified by us? The game engine will crash and our users are gonna be very upset.

Please consider creating an error handling system for your library :)
One of the many options are C++ exceptions. They work really great and - if you use exception handlers - clean up after themselves. You could also cook up something unique. Just please do not make the game engine crash if there is an error in assets!

Thanks.

**Comment by JayFoxRox** [comment]
asserts won't crash. It's a controlled exit because something did not happen as intended.

I'd recommend replacing the assert macro with something appropriate for your project (which may or may not be some kind of error handling; possibly something with an error flag until other systems are in place).
Also note, that even if librw is more complete it probably will hit an assertion once in a while. So you must have a way to handle this gracefully.
